[package]
name = "make-your-reads"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-or-later"
[[bin]]
name = "mkyr"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.58", features = ["derive"] }
